parameters:
- name: pluginsToDeploy
  type: object
  default:
  - systemlink-notebook-datasource

trigger:
  branches:
    include:
      - azure-pipelines-2

pool:
  name: DevCentral-Skyline

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- ${{ each pluginDir in parameters.pluginsToDeploy }}:
  - task: Npm@1
    inputs:
      command: 'ci'
      workingDir: ${{ pluginDir }}
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '${{ pluginDir }}'
      customCommand: 'run build'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '${{ pluginDir }}/dist'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'invoke-webrequest -method put -infile $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip https://transfer.sh'