trigger:
  branches:
    include:
      - azure-pipelines-2

pool:
  name: DevCentral-Skyline

steps:
- task: Bash@3
  inputs:
    filePath: 'build.sh'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls build/plugins'