parameters:
- name: pluginsToDeploy
  type: object
  default:
  - systemlink-notebook-datasource

trigger:
  branches:
    include:
      - azure-pipelines-2

pool:
  name: DevCentral-Skyline

steps:
- ${{ each value in parameters.pluginsToDeploy }}:
  - task: Npm@1
    inputs:
      command: 'ci'
      workingDir: ${{ value }}