parameters:
- name: pluginsToDeploy
  type: object
  default:
  - systemlink-notebook-datasource

trigger:
  branches:
    include:
      - azure-pipelines-2

pool:
  name: DevCentral-Skyline

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- ${{ each plugin in parameters.pluginsToDeploy }}:
  - task: Npm@1
    inputs:
      command: 'ci'
      workingDir: ${{ plugin }}
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '${{ plugin }}'
      customCommand: 'run build'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '${{ plugin }}/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.StagingDirectory)/${{ plugin }}-$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: ArtifactoryGenericUpload@2
    inputs:
      artifactoryService: 'Repos-Artifactory'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "$(Build.StagingDirectory)/${{ plugin }}-$(Build.BuildId).zip",
              "target": "rnd-app-builds/grafana-plugins/${{ plugin }}/"
            },
            {
              "pattern": "$(Build.StagingDirectory)/${{ plugin }}-$(Build.BuildId).zip",
              "target": "rnd-app-builds/grafana-plugins/${{ plugin }}/${{ plugin }}-latest"
            }
          ]
        }
      failNoOp: true