parameters:
- name: pluginsToDeploy
  type: object
  default:
  - systemlink-notebook-datasource

trigger:
  branches:
    include:
      - azure-pipelines-2

pool:
  name: DevCentral-Skyline

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- ${{ each value in parameters.pluginsToDeploy }}:
  - task: Npm@1
    inputs:
      command: 'ci'
      workingDir: ${{ value }}