import { DataQueryRequest } from "@grafana/data";
import { getTemplateSrv } from "@grafana/runtime";
import { cloneDeep } from "lodash";
import { DieType, FilterWafersQuery, RequestType, Wafer } from "types";

export function doMockRequest(options: DataQueryRequest<FilterWafersQuery>, query: FilterWafersQuery) {
    let result = cloneDeep(mockWafers);
    result = filterByDate(result, options);
    result = filterByWaferId(result, query);
    result = filterOutGoodDice(result, query);

    return Promise.resolve(result);
}

function filterByDate(data: Wafer[], options: DataQueryRequest<FilterWafersQuery>) {
    if(options.range.from) {
      data = data.filter(wafer => wafer.resultDate > options.range.from.toDate());
    }
    if(options.range.to) {
      data = data.filter(wafer => wafer.resultDate < options.range.to.toDate());
    }
    return data;
}

function filterByWaferId(data: Wafer[], query: FilterWafersQuery) {
    let waferDiceId = query.waferDiceId;
    if(waferDiceId && (query.requestType === RequestType.GetDice || query.requestType === RequestType.GetWafer)){
        const templateService = getTemplateSrv();
        const variable = templateService.getVariables().filter(variable => `\$${variable.name}` === query.waferDiceId)[0];
        if(variable) {
        waferDiceId = templateService.replace(query.waferDiceId);
        }
        return data.filter(wafer => wafer.id == waferDiceId);
    }
    return data;
}

function filterOutGoodDice(data: Wafer[], query: FilterWafersQuery) {
    if(query.filterOutGoodDice && query.requestType === RequestType.GetDice) {
      for(let wafer of data){
        wafer.dice = wafer.dice.filter(die => die.type != DieType.Good);
      }
    }
    return data;
}
  
  
const mockWafers: Wafer[] =
    [
      {
        id: "1",
        name: "Wafer 1",
        source: "Product 1 / Operation 2 / Lot 1",
        yieldBefore: "90%",
        totalGoodUnits: "30",
        yieldAfterGDBN: "60%",
        yieldLoss: "30%",
        totalOutliers: "5",
        resultDate: new Date(new Date().setDate(new Date().getDate() -1)),
        dice: [
          { x: 1, y: 3, type: DieType.Good },
          { x: 1, y: 4, type: DieType.Good },
          { x: 2, y: 2, type: DieType.Good },
          { x: 2, y: 3, type: DieType.Bad },
          { x: 2, y: 4, type: DieType.Outlier },
          { x: 2, y: 5, type: DieType.Good },
          { x: 3, y: 1, type: DieType.Good },
          { x: 3, y: 2, type: DieType.Good },
          { x: 3, y: 3, type: DieType.Bad },
          { x: 3, y: 4, type: DieType.Good },
          { x: 3, y: 5, type: DieType.Good },
          { x: 3, y: 6, type: DieType.Good },
          { x: 4, y: 1, type: DieType.Outlier },
          { x: 4, y: 2, type: DieType.Bad },
          { x: 4, y: 3, type: DieType.Good },
          { x: 4, y: 4, type: DieType.Good },
          { x: 4, y: 5, type: DieType.Bad },
          { x: 4, y: 6, type: DieType.Good },
          { x: 5, y: 2, type: DieType.Good },
          { x: 5, y: 3, type: DieType.Outlier },
          { x: 5, y: 4, type: DieType.Good },
          { x: 5, y: 5, type: DieType.Good },
          { x: 6, y: 3, type: DieType.Good },
          { x: 6, y: 4, type: DieType.Good },
        ]
      },
      {
        id: "2",
        name: "Wafer 2",
        source: "Product 23 / Operation 21 / Lot 11",
        yieldBefore: "95%",
        totalGoodUnits: "75",
        yieldAfterGDBN: "90%",
        yieldLoss: "5%",
        totalOutliers: "6",
        resultDate: new Date(new Date().setHours(new Date().getHours() -1)),
        dice:  [
          { x: 7, y: 1, type: DieType.Good },
          { x: 8, y: 1, type: DieType.Good },
          { x: 9, y: 1, type: DieType.Good },
          { x: 10, y: 1, type: DieType.Good },
          { x: 11, y: 1, type: DieType.Good },
          { x: 12, y: 1, type: DieType.Good },
          
          { x: 5, y: 2, type: DieType.Good },
          { x: 6, y: 2, type: DieType.Good },
          { x: 7, y: 2, type: DieType.Good },
          { x: 8, y: 2, type: DieType.Good },
          { x: 9, y: 2, type: DieType.Good },
          { x: 10, y: 2, type: DieType.Bad },
          { x: 11, y: 2, type: DieType.Good },
          { x: 12, y: 2, type: DieType.Good },
          { x: 13, y: 2, type: DieType.Good },
          { x: 14, y: 2, type: DieType.Good },

          { x: 4, y: 3, type: DieType.Good },
          { x: 5, y: 3, type: DieType.Good },
          { x: 6, y: 3, type: DieType.Good },
          { x: 7, y: 3, type: DieType.Good },
          { x: 8, y: 3, type: DieType.Good },
          { x: 9, y: 3, type: DieType.Good },
          { x: 10, y: 3, type: DieType.Good },
          { x: 11, y: 3, type: DieType.Good },
          { x: 12, y: 3, type: DieType.Bad },
          { x: 13, y: 3, type: DieType.Good },
          { x: 14, y: 3, type: DieType.Good },
          { x: 15, y: 3, type: DieType.Good },
          { x: 16, y: 3, type: DieType.Good },

          { x: 3, y: 4, type: DieType.Good },
          { x: 4, y: 4, type: DieType.Good },
          { x: 5, y: 4, type: DieType.Good },
          { x: 6, y: 4, type: DieType.Good },
          { x: 7, y: 4, type: DieType.Good },
          { x: 8, y: 4, type: DieType.Good },
          { x: 9, y: 4, type: DieType.Good },
          { x: 10, y: 4, type: DieType.Good },
          { x: 11, y: 4, type: DieType.Outlier },
          { x: 12, y: 4, type: DieType.Bad },
          { x: 13, y: 4, type: DieType.Good },
          { x: 14, y: 4, type: DieType.Good },
          { x: 15, y: 4, type: DieType.Good },
          { x: 16, y: 4, type: DieType.Good },
          { x: 17, y: 4, type: DieType.Good },

          { x: 2, y: 5, type: DieType.Good },
          { x: 3, y: 5, type: DieType.Good },
          { x: 4, y: 5, type: DieType.Good },
          { x: 5, y: 5, type: DieType.Good },
          { x: 6, y: 5, type: DieType.Good },
          { x: 7, y: 5, type: DieType.Outlier },
          { x: 8, y: 5, type: DieType.Good },
          { x: 9, y: 5, type: DieType.Good },
          { x: 10, y: 5, type: DieType.Good },
          { x: 11, y: 5, type: DieType.Good },
          { x: 12, y: 5, type: DieType.Good },
          { x: 13, y: 5, type: DieType.Good },
          { x: 14, y: 5, type: DieType.Bad },
          { x: 15, y: 5, type: DieType.Good },
          { x: 16, y: 5, type: DieType.Good },
          { x: 17, y: 5, type: DieType.Good },

          { x: 2, y: 6, type: DieType.Good },
          { x: 3, y: 6, type: DieType.Good },
          { x: 4, y: 6, type: DieType.Good },
          { x: 5, y: 6, type: DieType.Good },
          { x: 6, y: 6, type: DieType.Good },
          { x: 7, y: 6, type: DieType.Good },
          { x: 8, y: 6, type: DieType.Good },
          { x: 9, y: 6, type: DieType.Good },
          { x: 10, y: 6, type: DieType.Bad },
          { x: 11, y: 6, type: DieType.Good },
          { x: 12, y: 6, type: DieType.Good },
          { x: 13, y: 6, type: DieType.Good },
          { x: 14, y: 6, type: DieType.Good },
          { x: 15, y: 6, type: DieType.Good },
          { x: 16, y: 6, type: DieType.Good },
          { x: 17, y: 6, type: DieType.Good },
          { x: 18, y: 6, type: DieType.Good },

          { x: 1, y: 7, type: DieType.Good },
          { x: 2, y: 7, type: DieType.Good },
          { x: 3, y: 7, type: DieType.Good },
          { x: 4, y: 7, type: DieType.Good },
          { x: 5, y: 7, type: DieType.Good },
          { x: 6, y: 7, type: DieType.Good },
          { x: 7, y: 7, type: DieType.Bad },
          { x: 8, y: 7, type: DieType.Good },
          { x: 9, y: 7, type: DieType.Good },
          { x: 10, y: 7, type: DieType.Good },
          { x: 11, y: 7, type: DieType.Good },
          { x: 12, y: 7, type: DieType.Bad },
          { x: 13, y: 7, type: DieType.Good },
          { x: 14, y: 7, type: DieType.Good },
          { x: 15, y: 7, type: DieType.Good },
          { x: 16, y: 7, type: DieType.Good },
          { x: 17, y: 7, type: DieType.Good },
          { x: 18, y: 7, type: DieType.Good },

          { x: 1, y: 8, type: DieType.Good },
          { x: 2, y: 8, type: DieType.Good },
          { x: 3, y: 8, type: DieType.Good },
          { x: 4, y: 8, type: DieType.Good },
          { x: 5, y: 8, type: DieType.Good },
          { x: 6, y: 8, type: DieType.Good },
          { x: 7, y: 8, type: DieType.Good },
          { x: 8, y: 8, type: DieType.Good },
          { x: 9, y: 8, type: DieType.Good },
          { x: 10, y: 8, type: DieType.Good },
          { x: 11, y: 8, type: DieType.Good },
          { x: 12, y: 8, type: DieType.Good },
          { x: 13, y: 8, type: DieType.Good },
          { x: 14, y: 8, type: DieType.Good },
          { x: 15, y: 8, type: DieType.Good },
          { x: 16, y: 8, type: DieType.Good },
          { x: 17, y: 8, type: DieType.Good },
          { x: 18, y: 8, type: DieType.Good },
          { x: 19, y: 8, type: DieType.Good },

          { x: 1, y: 9, type: DieType.Good },
          { x: 2, y: 9, type: DieType.Good },
          { x: 3, y: 9, type: DieType.Good },
          { x: 4, y: 9, type: DieType.Good },
          { x: 5, y: 9, type: DieType.Good },
          { x: 6, y: 9, type: DieType.Good },
          { x: 7, y: 9, type: DieType.Good },
          { x: 8, y: 9, type: DieType.Good },
          { x: 9, y: 9, type: DieType.Good },
          { x: 10, y: 9, type: DieType.Good },
          { x: 11, y: 9, type: DieType.Good },
          { x: 12, y: 9, type: DieType.Good },
          { x: 13, y: 9, type: DieType.Good },
          { x: 14, y: 9, type: DieType.Good },
          { x: 15, y: 9, type: DieType.Good },
          { x: 16, y: 9, type: DieType.Good },
          { x: 17, y: 9, type: DieType.Good },
          { x: 18, y: 9, type: DieType.Good },
          { x: 19, y: 9, type: DieType.Good },

          { x: 1, y: 10, type: DieType.Good },
          { x: 2, y: 10, type: DieType.Good },
          { x: 3, y: 10, type: DieType.Good },
          { x: 4, y: 10, type: DieType.Good },
          { x: 5, y: 10, type: DieType.Good },
          { x: 6, y: 10, type: DieType.Good },
          { x: 7, y: 10, type: DieType.Good },
          { x: 8, y: 10, type: DieType.Good },
          { x: 9, y: 10, type: DieType.Good },
          { x: 10, y: 10, type: DieType.Good },
          { x: 11, y: 10, type: DieType.Good },
          { x: 12, y: 10, type: DieType.Good },
          { x: 13, y: 10, type: DieType.Good },
          { x: 14, y: 10, type: DieType.Good },
          { x: 15, y: 10, type: DieType.Good },
          { x: 16, y: 10, type: DieType.Good },
          { x: 17, y: 10, type: DieType.Good },
          { x: 18, y: 10, type: DieType.Good },
          { x: 19, y: 10, type: DieType.Good },

          { x: 1, y: 11, type: DieType.Good },
          { x: 2, y: 11, type: DieType.Good },
          { x: 3, y: 11, type: DieType.Good },
          { x: 4, y: 11, type: DieType.Good },
          { x: 5, y: 11, type: DieType.Good },
          { x: 6, y: 11, type: DieType.Good },
          { x: 7, y: 11, type: DieType.Good },
          { x: 8, y: 11, type: DieType.Good },
          { x: 9, y: 11, type: DieType.Good },
          { x: 10, y: 11, type: DieType.Good },
          { x: 11, y: 11, type: DieType.Good },
          { x: 12, y: 11, type: DieType.Good },
          { x: 13, y: 11, type: DieType.Good },
          { x: 14, y: 11, type: DieType.Good },
          { x: 15, y: 11, type: DieType.Good },
          { x: 16, y: 11, type: DieType.Good },
          { x: 17, y: 11, type: DieType.Good },
          { x: 18, y: 11, type: DieType.Good },
          { x: 19, y: 11, type: DieType.Good },

          { x: 1, y: 12, type: DieType.Good },
          { x: 2, y: 12, type: DieType.Good },
          { x: 3, y: 12, type: DieType.Good },
          { x: 4, y: 12, type: DieType.Good },
          { x: 5, y: 12, type: DieType.Good },
          { x: 6, y: 12, type: DieType.Good },
          { x: 7, y: 12, type: DieType.Good },
          { x: 8, y: 12, type: DieType.Good },
          { x: 9, y: 12, type: DieType.Good },
          { x: 10, y: 12, type: DieType.Good },
          { x: 11, y: 12, type: DieType.Good },
          { x: 12, y: 12, type: DieType.Good },
          { x: 13, y: 12, type: DieType.Good },
          { x: 14, y: 12, type: DieType.Good },
          { x: 15, y: 12, type: DieType.Good },
          { x: 16, y: 12, type: DieType.Good },
          { x: 17, y: 12, type: DieType.Good },
          { x: 18, y: 12, type: DieType.Good },

          { x: 2, y: 13, type: DieType.Good },
          { x: 3, y: 13, type: DieType.Good },
          { x: 4, y: 13, type: DieType.Good },
          { x: 5, y: 13, type: DieType.Good },
          { x: 6, y: 13, type: DieType.Good },
          { x: 7, y: 13, type: DieType.Good },
          { x: 8, y: 13, type: DieType.Good },
          { x: 9, y: 13, type: DieType.Good },
          { x: 10, y: 13, type: DieType.Good },
          { x: 11, y: 13, type: DieType.Good },
          { x: 12, y: 13, type: DieType.Good },
          { x: 13, y: 13, type: DieType.Good },
          { x: 14, y: 13, type: DieType.Good },
          { x: 15, y: 13, type: DieType.Good },
          { x: 16, y: 13, type: DieType.Good },
          { x: 17, y: 13, type: DieType.Good },
          { x: 18, y: 13, type: DieType.Good },

          { x: 2, y: 14, type: DieType.Good },
          { x: 3, y: 14, type: DieType.Good },
          { x: 4, y: 14, type: DieType.Good },
          { x: 5, y: 14, type: DieType.Good },
          { x: 6, y: 14, type: DieType.Good },
          { x: 7, y: 14, type: DieType.Good },
          { x: 8, y: 14, type: DieType.Good },
          { x: 9, y: 14, type: DieType.Good },
          { x: 10, y: 14, type: DieType.Good },
          { x: 11, y: 14, type: DieType.Good },
          { x: 12, y: 14, type: DieType.Good },
          { x: 13, y: 14, type: DieType.Good },
          { x: 14, y: 14, type: DieType.Good },
          { x: 15, y: 14, type: DieType.Good },
          { x: 16, y: 14, type: DieType.Good },
          { x: 17, y: 14, type: DieType.Good },
          { x: 18, y: 14, type: DieType.Good },

          { x: 3, y: 15, type: DieType.Good },
          { x: 4, y: 15, type: DieType.Good },
          { x: 5, y: 15, type: DieType.Good },
          { x: 6, y: 15, type: DieType.Outlier },
          { x: 7, y: 15, type: DieType.Good },
          { x: 8, y: 15, type: DieType.Good },
          { x: 9, y: 15, type: DieType.Good },
          { x: 10, y: 15, type: DieType.Good },
          { x: 11, y: 15, type: DieType.Good },
          { x: 12, y: 15, type: DieType.Good },
          { x: 13, y: 15, type: DieType.Good },
          { x: 14, y: 15, type: DieType.Good },
          { x: 15, y: 15, type: DieType.Outlier },
          { x: 16, y: 15, type: DieType.Good },
          { x: 17, y: 15, type: DieType.Good },
          
          { x: 3, y: 16, type: DieType.Good },
          { x: 4, y: 16, type: DieType.Good },
          { x: 5, y: 16, type: DieType.Good },
          { x: 6, y: 16, type: DieType.Outlier },
          { x: 7, y: 16, type: DieType.Good },
          { x: 8, y: 16, type: DieType.Good },
          { x: 9, y: 16, type: DieType.Good },
          { x: 10, y: 16, type: DieType.Good },
          { x: 11, y: 16, type: DieType.Good },
          { x: 12, y: 16, type: DieType.Good },
          { x: 13, y: 16, type: DieType.Good },
          { x: 14, y: 16, type: DieType.Outlier },
          { x: 15, y: 16, type: DieType.Good },
          { x: 16, y: 16, type: DieType.Good },

          { x: 4, y: 17, type: DieType.Good },
          { x: 5, y: 17, type: DieType.Good },
          { x: 6, y: 17, type: DieType.Good },
          { x: 7, y: 17, type: DieType.Good },
          { x: 8, y: 17, type: DieType.Good },
          { x: 9, y: 17, type: DieType.Good },
          { x: 10, y: 17, type: DieType.Good },
          { x: 11, y: 17, type: DieType.Good },
          { x: 12, y: 17, type: DieType.Bad },
          { x: 13, y: 17, type: DieType.Bad },
          { x: 14, y: 17, type: DieType.Bad },
          { x: 15, y: 17, type: DieType.Bad },

          { x: 6, y: 18, type: DieType.Good },
          { x: 7, y: 18, type: DieType.Good },
          { x: 8, y: 18, type: DieType.Good },
          { x: 9, y: 18, type: DieType.Good },
          { x: 10, y: 18, type: DieType.Good },
          { x: 11, y: 18, type: DieType.Bad },
          { x: 12, y: 18, type: DieType.Bad },
          { x: 13, y: 18, type: DieType.Good },
          { x: 14, y: 18, type: DieType.Good },

          { x: 8, y: 19, type: DieType.Good },
          { x: 9, y: 19, type: DieType.Good },
          { x: 10, y: 19, type: DieType.Good },
          { x: 11, y: 19, type: DieType.Good },
        ]
      }
    ];