apiVersion: 1

datasources:
  - name: SystemLink Notebooks
    type: systemlink-notebook-datasource
    access: direct
    url: /
  - name: SystemLink Systems
    type: ni-slsystem-datasource
    uid: system
    access: direct
    url: /
  - name: SystemLink Tags
    type: ni-sltag-datasource
    uid: tag
    access: direct
    url: /
  - name: SystemLink Workspaces
    type: ni-slworkspace-datasource
    uid: workspace
    access: direct
    url: /
  - name: SystemLink Test Monitor
    type: ni-systemlink-test-monitor
    access: direct
    url: /
  - name: SystemLink Alarms
    type:: ni-slalarms-datasource
    uid: alarms
    access: direct
    url: /
  - name: SystemLink Products
    type: ni-slproducts-datasource
    uid: products
    access: direct
    url: /
  - name: SystemLink Test Results
    type: ni-sltestresults-datasource
    uid: testresults
    access: direct
    url: /
  - name: SystemLink Assets
    type: "ni-slasset-datasource"
    uid: assets
    access: direct
    url: /