name: CI

on:
  push:
    branches:
      - master
    paths-ignore: 
      - '**.yml'
      - '**.md'
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Run build script
      run: sh build.sh
    
    - name: Set current date as env variable
      if: ${{ github.event_name == 'push' }}
      run: echo "date_now=$(date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV

    - name: Create a Release
      if: ${{ github.event_name == 'push' }}
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.date_now }}
        release_name: ${{ env.date_now }}

    - name: Upload a Release Asset
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/grafana-plugins.zip
        asset_name: ${{ env.date_now }}-grafana-plugins.zip
        asset_content_type: application/zip
